---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 9200, host: 9200}]
    - ["forwarded_port", {guest: 9300, host: 9300}]
    - ["forwarded_port", {guest: 5601, host: 5601}]
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[eas-logstash::server]
    attributes:
